# Generated by Django 5.1.2 on 2024-11-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Background',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('body_uz', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Fon',
                'verbose_name_plural': 'Fonlar',
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='banner_images/')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('body_uz', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Banner',
                'verbose_name_plural': 'Bannerlar',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('surname', models.CharField(max_length=255)),
                ('age', models.SmallIntegerField()),
                ('number', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Kontakt',
                'verbose_name_plural': 'Kontaktlar',
            },
        ),
        migrations.CreateModel(
            name='Employ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='employ_images/')),
                ('fullname', models.CharField(max_length=255)),
                ('fullname_uz', models.CharField(max_length=255, null=True)),
                ('fullname_en', models.CharField(max_length=255, null=True)),
                ('fullname_ru', models.CharField(max_length=255, null=True)),
                ('job', models.CharField(max_length=255)),
                ('job_uz', models.CharField(max_length=255, null=True)),
                ('job_en', models.CharField(max_length=255, null=True)),
                ('job_ru', models.CharField(max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Xodim',
                'verbose_name_plural': 'Xodimlar',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/')),
                ('title', models.CharField(max_length=255)),
                ('title_uz', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('body', models.TextField()),
                ('body_uz', models.TextField(null=True)),
                ('body_en', models.TextField(null=True)),
                ('body_ru', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
            },
        ),
    ]
